name: pddikti-api
services:
  - name: pddikti-api
    github:
      repository: Nant361/dsafdsfdsfsafdsfdsafasdf
      branch: main
    instance_type: nano
    scalability:
      min_instances: 1
      max_instances: 1
    ports:
      - port: 8000
        protocol: tcp
    healthcheck:
      tcp:
        port: 8000
        grace_period: 5s
        interval: 30s
        restart_limit: 3
        timeout: 5s
    builder:
      name: docker
      dockerfile_path: Dockerfile
      build_args:
        - name: PYTHON_VERSION
          value: "3.11"
      registry:
        name: koyeb 
